"""Exact API reference for the pinned engine — generated by the engine itself.

``godot --headless --doctool <dir>`` dumps the *ClassDB* of the running binary as
XML: every class, its parent, every method with parameter names/types/defaults,
every property, signal, constant, enum, GDScript annotation and Variant
constructor — for exactly the version we pin (``4.7.2.stable.official.ed1daf0bf``
produces 1,076 files in ~1 s). That is the strongest possible defence against
the #1 failure mode of LLMs writing GDScript: *inventing or misremembering APIs*
(Godot 3 names, wrong argument lists, renamed properties). The model can look a
signature up before writing code, and the verification pipeline lints scripts
against the same index.

Descriptions are **not** part of the ClassDB dump. If a checkout of the official
``doc/classes`` for the same tag is available (``--docs-dir``), the class XML
files are copied next to the dump before ``--doctool`` runs; the engine then
merges the prose into the generated files (this is exactly how the Godot repo
itself regenerates its documentation).

The index is cached as JSON under ``$XDG_CACHE_HOME/godotai/apiref/<tag>/`` (or
``$GODOTAI_APIREF_DIR``) and rebuilt when the engine pin or the index format
changes.
"""
from __future__ import annotations

import difflib
import json
import os
import re
import shutil
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from .config import EngineConfig
from .godot import Godot

INDEX_FORMAT = 3
ENV_APIREF_DIR = "GODOTAI_APIREF_DIR"
GLOBAL_CLASSES = ("@GDScript", "@GlobalScope")   # where free functions / annotations / global enums live
MEMBER_KINDS = ("methods", "members", "signals", "constants", "annotations", "constructors")

# Types GDScript knows that may not appear as classes in every dump.
BUILTIN_TYPES = {
    "void", "null", "Variant", "bool", "int", "float", "String", "StringName", "NodePath", "RID", "Callable",
    "Signal", "Array", "Dictionary", "Object", "Vector2", "Vector2i", "Vector3", "Vector3i", "Vector4", "Vector4i",
    "Rect2", "Rect2i", "Transform2D", "Transform3D", "Basis", "Plane", "Quaternion", "AABB", "Projection", "Color",
    "PackedByteArray", "PackedInt32Array", "PackedInt64Array", "PackedFloat32Array", "PackedFloat64Array",
    "PackedStringArray", "PackedVector2Array", "PackedVector3Array", "PackedVector4Array", "PackedColorArray",
}


class ApiRefError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# Building the index
# ---------------------------------------------------------------------------
def cache_dir(engine: EngineConfig) -> Path:
    override = os.environ.get(ENV_APIREF_DIR)
    if override:
        return Path(override).expanduser()
    base = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    return base / "godotai" / "apiref" / engine.tag


def index_path(engine: EngineConfig) -> Path:
    return cache_dir(engine) / "index.json"


def _is_class_xml(path: Path) -> bool:
    """True when *path* looks like a Godot class reference file (root element ``<class``)."""
    try:
        with open(path, "rb") as fh:
            head = fh.read(600)
    except OSError:
        return False
    return b"<class " in head


def generate_xml(godot: Godot, out_dir: Path, docs_dir: Path | None = None, timeout: int = 300) -> Path:
    """Run ``--doctool`` into *out_dir*; merge prose from *docs_dir* when given."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if docs_dir:
        docs_dir = Path(docs_dir)
        target = out_dir / "doc" / "classes"
        target.mkdir(parents=True, exist_ok=True)
        n = 0
        for xml in docs_dir.rglob("*.xml"):
            if _is_class_xml(xml):
                shutil.copy2(xml, target / xml.name)
                n += 1
        if n == 0:
            raise ApiRefError(f"no class reference .xml files found under {docs_dir}")
    res = godot.run(["--headless", "--doctool", str(out_dir)], timeout=timeout)
    files = list(out_dir.rglob("*.xml"))
    if not files:
        raise ApiRefError(f"--doctool produced no XML (exit {res.returncode}): {res.output[-800:]}")
    return out_dir


def _text(el: ET.Element | None, limit: int) -> str:
    if el is None or el.text is None:
        return ""
    return " ".join(el.text.split())[:limit]


def _typed(el: ET.Element, default: str = "") -> str:
    """Type of a param/return/member; enum-typed ints are shown by their enum name (as the docs do)."""
    enum = el.get("enum")
    if enum:
        return enum + (" (bitfield)" if el.get("is_bitfield") == "true" else "")
    return el.get("type", default)


def _params(el: ET.Element) -> list[dict[str, str]]:
    out = []
    for p in sorted(el.findall("param"), key=lambda e: int(e.get("index", "0"))):
        d = {"name": p.get("name", ""), "type": _typed(p)}
        if p.get("default") is not None:
            d["default"] = p.get("default", "")
        out.append(d)
    return out


def _flags(el: ET.Element, entry: dict[str, Any]) -> None:
    if el.get("deprecated") is not None:
        entry["deprecated"] = el.get("deprecated") or "deprecated"
    if el.get("experimental") is not None:
        entry["experimental"] = el.get("experimental") or "experimental"


def _callable(m: ET.Element) -> dict[str, Any]:
    ret = m.find("return")
    entry: dict[str, Any] = {
        "name": m.get("name", ""),
        "return": _typed(ret, "void") if ret is not None else "void",
        "params": _params(m),
        "qualifiers": m.get("qualifiers", ""),
        "description": _text(m.find("description"), 600),
    }
    _flags(m, entry)
    return entry


def parse_class_xml(path: Path) -> dict[str, Any] | None:
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        return None
    if root.tag != "class":
        return None
    cls: dict[str, Any] = {
        "name": root.get("name", path.stem),
        "inherits": root.get("inherits", ""),
        "brief": _text(root.find("brief_description"), 400),
        "description": _text(root.find("description"), 1500),
        "methods": [], "members": [], "signals": [], "constants": [], "annotations": [], "constructors": [],
    }
    _flags(root, cls)
    for m in root.findall("./methods/method"):
        cls["methods"].append(_callable(m))
    for m in root.findall("./constructors/constructor"):
        cls["constructors"].append(_callable(m))
    for m in root.findall("./annotations/annotation"):
        cls["annotations"].append(_callable(m))
    for m in root.findall("./members/member"):
        entry = {
            "name": m.get("name", ""), "type": _typed(m),
            "default": m.get("default", ""), "setter": m.get("setter", ""), "getter": m.get("getter", ""),
            "description": _text(m, 400),
        }
        _flags(m, entry)
        cls["members"].append(entry)
    for s in root.findall("./signals/signal"):
        entry = {"name": s.get("name", ""), "params": _params(s), "description": _text(s.find("description"), 400)}
        _flags(s, entry)
        cls["signals"].append(entry)
    for c in root.findall("./constants/constant"):
        entry = {"name": c.get("name", ""), "value": c.get("value", ""), "enum": c.get("enum", ""),
                 "description": _text(c, 300)}
        _flags(c, entry)
        cls["constants"].append(entry)
    return cls


def parse_xml_dir(root: Path) -> dict[str, dict[str, Any]]:
    classes: dict[str, dict[str, Any]] = {}
    for xml in sorted(Path(root).rglob("*.xml")):
        cls = parse_class_xml(xml)
        if cls:
            classes[cls["name"]] = cls
    return classes


def format_method(m: dict[str, Any]) -> str:
    params = ", ".join(
        f"{p['name']}: {p['type']}" + (f" = {p['default']}" if "default" in p else "") for p in m["params"])
    q = f" {m['qualifiers']}" if m.get("qualifiers") else ""
    dep = "  [DEPRECATED]" if m.get("deprecated") else ""
    return f"{m['name']}({params}) -> {m['return']}{q}{dep}"


def _sig_params(entry: dict[str, Any]) -> str:
    return ", ".join(p["name"] + ": " + p["type"] for p in entry["params"])


@dataclass
class ApiIndex:
    engine_tag: str
    engine_version: str
    classes: dict[str, dict[str, Any]]
    has_descriptions: bool = False
    path: Path | None = None
    _lower: dict[str, str] = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        self._lower = {n.lower(): n for n in self.classes}

    # -- lookups ------------------------------------------------------------
    def has(self, name: str) -> bool:
        return name in self.classes

    def resolve(self, name: str) -> str | None:
        """Exact name, else case-insensitive match."""
        if name in self.classes:
            return name
        return self._lower.get(name.lower())

    def suggest(self, name: str, n: int = 5) -> list[str]:
        hits = difflib.get_close_matches(name, list(self.classes), n=n, cutoff=0.6)
        legacy = LEGACY_CLASS_RENAMES.get(name)
        if legacy and legacy in self.classes and legacy not in hits:
            hits.insert(0, legacy)
        return hits

    def ancestors(self, name: str) -> list[str]:
        out: list[str] = []
        cur = self.classes.get(name, {}).get("inherits", "")
        while cur and cur in self.classes and cur not in out:
            out.append(cur)
            cur = self.classes[cur].get("inherits", "")
        return out

    def find_member(self, cls_name: str, member: str) -> tuple[str, str, dict[str, Any]] | None:
        """Return (owner_class, kind, entry) searching the class then its ancestors."""
        for owner in [cls_name, *self.ancestors(cls_name)]:
            c = self.classes.get(owner)
            if not c:
                continue
            for kind in MEMBER_KINDS:
                for entry in c.get(kind, []):
                    if entry["name"] == member:
                        return owner, kind, entry
        return None

    def find_global(self, name: str) -> tuple[str, str, dict[str, Any]] | None:
        """Free functions (``lerp``, ``randf_range``), annotations (``@export``), global enums/constants."""
        for g in GLOBAL_CLASSES:
            hit = self.find_member(g, name)
            if hit:
                return hit
        return None

    def search(self, query: str, limit: int = 20) -> list[str]:
        terms = [t for t in re.findall(r"[a-z0-9_@]+", query.lower()) if len(t) > 1]
        if not terms:
            return []
        scored: list[tuple[int, str]] = []
        for cname, c in self.classes.items():
            cl = cname.lower()
            cscore = sum(3 for t in terms if t in cl)
            if cscore:
                scored.append((cscore + 1, f"class {cname}" + (f" — {c['brief']}" if c.get("brief") else "")))
            for kind in MEMBER_KINDS:
                for entry in c.get(kind, []):
                    nl = entry["name"].lower()
                    s = sum(2 for t in terms if t in nl)
                    if not s:
                        continue
                    if any(t in cl for t in terms):      # query names both the class and the member
                        s += 3
                    s += 2 * sum(1 for t in terms if t == nl) + sum(1 for t in terms if t == cl)  # exact hits
                    scored.append((s, f"{cname}.{self._brief_entry(kind, entry)}"))
        scored.sort(key=lambda x: (-x[0], x[1]))
        seen: set[str] = set()
        out: list[str] = []
        for _, line in scored:
            if line not in seen:
                seen.add(line)
                out.append(line)
            if len(out) >= limit:
                break
        return out

    @staticmethod
    def _brief_entry(kind: str, entry: dict[str, Any]) -> str:
        if kind in ("methods", "constructors", "annotations"):
            return format_method(entry)
        if kind == "members":
            return f"{entry['name']}: {entry['type']}"
        if kind == "signals":
            return f"{entry['name']}({_sig_params(entry)})  (signal)"
        return f"{entry['name']} = {entry['value']}" + (f"  (enum {entry['enum']})" if entry.get("enum") else "")

    # -- rendering ----------------------------------------------------------
    def render_member(self, owner: str, kind: str, entry: dict[str, Any], asked: str | None = None) -> str:
        via = "" if (asked is None or owner == asked) else f" (inherited from {owner})"
        if kind in ("methods", "constructors", "annotations"):
            body = f"{owner}.{format_method(entry)}{via}"
        elif kind == "members":
            body = f"{owner}.{entry['name']}: {entry['type']}" + (f" = {entry['default']}" if entry.get("default") else "") + via
            if entry.get("setter") or entry.get("getter"):
                body += f"  (setter {entry.get('setter') or '-'}, getter {entry.get('getter') or '-'})"
        elif kind == "signals":
            body = f"signal {owner}.{entry['name']}({_sig_params(entry)}){via}"
        else:
            body = f"const {owner}.{entry['name']} = {entry['value']}" + (f" (enum {entry['enum']})" if entry.get("enum") else "") + via
        if entry.get("deprecated"):
            body += f"\n  DEPRECATED: {entry['deprecated']}"
        if entry.get("description"):
            body += "\n  " + entry["description"]
        return body

    def render_class(self, name: str, member: str | None = None, max_items: int = 80) -> str:
        real = self.resolve(name)
        if real is None:
            sugg = self.suggest(name)
            msg = f"class {name!r} does not exist in Godot {self.engine_tag}."
            if name in LEGACY_CLASS_RENAMES:
                msg += f" It is a Godot 3 name — in Godot 4 use {LEGACY_CLASS_RENAMES[name]}."
            elif sugg:
                msg += " Did you mean: " + ", ".join(sugg) + "?"
            return msg
        c = self.classes[real]
        if member:
            hit = self.find_member(real, member)
            if hit is None:
                names = [e["name"] for k in MEMBER_KINDS for e in c.get(k, [])]
                for anc in self.ancestors(real):
                    names += [e["name"] for k in MEMBER_KINDS for e in self.classes[anc].get(k, [])]
                close = difflib.get_close_matches(member, names, n=5, cutoff=0.6)
                g = self.find_global(member)
                extra = ""
                if g:
                    extra = f" It exists as a global: {self.render_member(g[0], g[1], g[2]).splitlines()[0]}"
                return (f"{real} has no member {member!r} in Godot {self.engine_tag}"
                        + (f"; did you mean: {', '.join(close)}?" if close else ".") + extra)
            owner, kind, entry = hit
            if kind == "constructors":   # Variant types have several overloads with the same name
                return "\n".join(self.render_member(owner, kind, e, asked=real)
                                 for e in self.classes[owner]["constructors"] if e["name"] == member)
            return self.render_member(owner, kind, entry, asked=real)
        lines = [f"class {real}" + (f" extends {c['inherits']}" if c["inherits"] else "") + f"   [Godot {self.engine_tag}]"]
        if c.get("deprecated"):
            lines.append(f"DEPRECATED: {c['deprecated']}")
        anc = self.ancestors(real)
        if anc:
            lines.append("inherits chain: " + " → ".join(anc))
        if c.get("brief"):
            lines.append(c["brief"])
        if c.get("constructors"):
            lines.append(f"constructors ({len(c['constructors'])}):")
            lines += ["  " + format_method(m) for m in c["constructors"][:max_items]]
        if c["members"]:
            lines.append(f"properties ({len(c['members'])}):")
            for m in c["members"][:max_items]:
                lines.append(f"  {m['name']}: {m['type']}" + (f" = {m['default']}" if m.get("default") else ""))
        if c["methods"]:
            lines.append(f"methods ({len(c['methods'])}):")
            lines += ["  " + format_method(m) for m in c["methods"][:max_items]]
            if len(c["methods"]) > max_items:
                lines.append(f"  … {len(c['methods']) - max_items} more (use api_search)")
        if c.get("annotations"):
            lines.append(f"annotations ({len(c['annotations'])}):")
            lines += ["  " + format_method(m) for m in c["annotations"][:max_items]]
        if c["signals"]:
            lines.append(f"signals ({len(c['signals'])}):")
            lines += [f"  {s['name']}({_sig_params(s)})" for s in c["signals"][:max_items]]
        if c["constants"]:
            enums = sorted({k["enum"] for k in c["constants"] if k.get("enum")})
            plain = [k for k in c["constants"] if not k.get("enum")]
            if enums:
                lines.append(f"enums ({len(enums)}): " + ", ".join(enums[:max_items]))
            if plain:
                lines.append(f"constants ({len(plain)}): " + ", ".join(k["name"] for k in plain[:max_items]))
        if anc:
            lines.append(f"(inherited members are not listed — query the parent classes, e.g. {anc[0]})")
        return "\n".join(lines)

    def render_enum(self, cls_name: str, enum: str) -> str | None:
        real = self.resolve(cls_name)
        if real is None:
            return None
        vals = [k for k in self.classes[real]["constants"] if k.get("enum") == enum]
        if not vals:
            return None
        return f"enum {real}.{enum}: " + ", ".join(f"{k['name']} = {k['value']}" for k in vals)

    # -- persistence --------------------------------------------------------
    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({
            "format": INDEX_FORMAT, "engine_tag": self.engine_tag, "engine_version": self.engine_version,
            "has_descriptions": self.has_descriptions, "classes": self.classes,
        }, ensure_ascii=False), encoding="utf-8")
        self.path = path

    @classmethod
    def load(cls, path: Path, expect_tag: str | None = None) -> "ApiIndex | None":
        try:
            data = json.loads(Path(path).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        if data.get("format") != INDEX_FORMAT:
            return None
        if expect_tag and data.get("engine_tag") != expect_tag:
            return None
        return cls(data["engine_tag"], data.get("engine_version", ""), data["classes"],
                   bool(data.get("has_descriptions")), Path(path))

    def stats(self) -> dict[str, int]:
        return {
            "classes": len(self.classes),
            "methods": sum(len(c["methods"]) for c in self.classes.values()),
            "properties": sum(len(c["members"]) for c in self.classes.values()),
            "signals": sum(len(c["signals"]) for c in self.classes.values()),
            "constants": sum(len(c["constants"]) for c in self.classes.values()),
        }


def load_index(engine: EngineConfig) -> ApiIndex | None:
    return ApiIndex.load(index_path(engine), expect_tag=engine.tag)


def build_index(godot: Godot, docs_dir: Path | None = None, force: bool = False,
                out_path: Path | None = None) -> ApiIndex:
    """Return the cached index for *godot*'s engine, generating it when needed."""
    engine = godot.engine
    path = out_path or index_path(engine)
    if not force:
        cached = ApiIndex.load(path, expect_tag=engine.tag)
        if cached is not None and (docs_dir is None or cached.has_descriptions):
            return cached
    tmp = Path(tempfile.mkdtemp(prefix="godotai-doctool-"))
    try:
        generate_xml(godot, tmp, docs_dir)
        classes = parse_xml_dir(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    if not classes:
        raise ApiRefError("doctool output could not be parsed")
    idx = ApiIndex(engine.tag, godot.version() or "", classes,
                   has_descriptions=any(c.get("brief") for c in classes.values()))
    idx.save(path)
    return idx


# ---------------------------------------------------------------------------
# Static lint of GDScript against the index + the official 3→4 rename list
# ---------------------------------------------------------------------------
# Source: "Upgrading from Godot 3 to Godot 4" (official docs), renamed nodes/resources/
# methods tables — https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html
LEGACY_CLASS_RENAMES: dict[str, str] = {
    "KinematicBody2D": "CharacterBody2D", "KinematicBody": "CharacterBody3D", "Spatial": "Node3D",
    "Sprite": "Sprite2D", "AnimatedSprite": "AnimatedSprite2D", "Position2D": "Marker2D", "Position3D": "Marker3D",
    "Area": "Area3D", "RayCast": "RayCast3D", "CollisionShape": "CollisionShape3D",
    "CollisionPolygon": "CollisionPolygon3D", "StaticBody": "StaticBody3D", "RigidBody": "RigidBody3D",
    "MeshInstance": "MeshInstance3D", "Camera": "Camera3D", "Light": "Light3D", "DirectionalLight": "DirectionalLight3D",
    "OmniLight": "OmniLight3D", "SpotLight": "SpotLight3D", "Path": "Path3D", "PathFollow": "PathFollow3D",
    "Skeleton": "Skeleton3D", "Particles2D": "GPUParticles2D", "Particles": "GPUParticles3D",
    "CPUParticles": "CPUParticles3D", "VisibilityNotifier2D": "VisibleOnScreenNotifier2D",
    "VisibilityEnabler2D": "VisibleOnScreenEnabler2D", "TextureProgress": "TextureProgressBar",
    "Tabs": "TabBar", "ToolButton": "Button", "WindowDialog": "Window", "PopupDialog": "Popup",
    "Reference": "RefCounted", "File": "FileAccess", "Directory": "DirAccess", "Quat": "Quaternion",
    "Transform": "Transform3D", "PoolByteArray": "PackedByteArray", "PoolIntArray": "PackedInt32Array",
    "PoolRealArray": "PackedFloat32Array", "PoolStringArray": "PackedStringArray",
    "PoolVector2Array": "PackedVector2Array", "PoolVector3Array": "PackedVector3Array",
    "PoolColorArray": "PackedColorArray", "StreamTexture": "CompressedTexture2D", "DynamicFont": "FontFile",
    "BitmapFont": "FontFile", "GIProbe": "VoxelGI", "BakedLightmap": "LightmapGI", "Listener": "AudioListener3D",
    "ARVRCamera": "XRCamera3D", "ARVROrigin": "XROrigin3D", "ARVRController": "XRController3D",
    "VisualServer": "RenderingServer", "Physics2DServer": "PhysicsServer2D", "PhysicsServer": "PhysicsServer3D",
    "Physics2DDirectSpaceState": "PhysicsDirectSpaceState2D", "LineShape2D": "WorldBoundaryShape2D",
    "Navigation2D": "NavigationServer2D", "InterpolatedCamera": "Camera3D", "YSort": "Node2D",
    "AnimationTreePlayer": "AnimationTree", "EditorSpatialGizmo": "EditorNode3DGizmo",
}
# Extra hint shown for renames that are not a 1:1 class swap.
LEGACY_CLASS_NOTES: dict[str, str] = {
    "YSort": "set `y_sort_enabled = true` on the Node2D/TileMapLayer instead",
    "Navigation2D": "use NavigationAgent2D + NavigationRegion2D",
    "ToolButton": "use Button with `flat = true`",
    "DynamicFont": "load the .ttf directly; size is set via theme override / Label.label_settings",
}

# (regex applied to a line with strings blanked to "" and comments removed, severity, hint)
# "error"   → definitely not Godot 4 / GDScript 2 (the engine would fail at parse or at run time)
# "warning" → almost always a Godot-3 leftover, but a same-named user method could exist
LEGACY_PATTERNS: tuple[tuple[re.Pattern[str], str, str], ...] = tuple((re.compile(p), s, h) for p, s, h in (
    (r"\byield\s*\(", "error", "Godot 3 `yield(...)` → `await signal_or_coroutine`"),
    (r"^\s*export(\s*\(|\s+var\b)", "error", "Godot 3 `export var` → `@export var`"),
    (r"^\s*onready\s+var\b", "error", "Godot 3 `onready var` → `@onready var`"),
    (r"^\s*tool\s*$", "error", "Godot 3 `tool` → `@tool`"),
    (r"\bsetget\b", "error", "Godot 3 `setget` → property with `set(value):` / `get:` blocks"),
    (r"\.instance\s*\(\s*\)", "error", "Godot 3 `PackedScene.instance()` → `instantiate()`"),
    (r"\.empty\s*\(\s*\)", "warning", "Godot 3 `.empty()` → `.is_empty()`"),
    (r"\bdeg2rad\s*\(", "error", "`deg2rad()` → `deg_to_rad()`"),
    (r"\brad2deg\s*\(", "error", "`rad2deg()` → `rad_to_deg()`"),
    (r"\bstepify\s*\(", "error", "`stepify()` → `snapped()`"),
    (r"\brand_range\s*\(", "error", "`rand_range()` → `randf_range()` (or `randi_range()`)"),
    (r"\.linear_interpolate\s*\(", "error", "`.linear_interpolate()` → `.lerp()`"),
    (r"\bstr2var\s*\(|\bvar2str\s*\(|\bbytes2var\s*\(|\bvar2bytes\s*\(", "error",
     "`*2*` helpers → `str_to_var/var_to_str/bytes_to_var/var_to_bytes`"),
    (r"\bparse_json\s*\(|\bto_json\s*\(|\bJSON\.parse\s*\(|\bJSON\.print\s*\(", "error",
     "Godot 3 JSON → `JSON.parse_string()` / `JSON.stringify()`"),
    (r"\bfuncref\s*\(", "error", "`funcref()` → `Callable(object, \"method\")` or just `object.method`"),
    # strings are blanked before matching, so Godot 3 connect("sig", target, "method") looks like connect("", x, "")
    (r"\bconnect\s*\(\s*\"\"\s*,\s*[^,()]+\s*,\s*\"\"", "error",
     "Godot 3 `connect(\"sig\", self, \"fn\")` → `sig.connect(fn)` (Callable-based)"),
    (r"\bTween\.new\s*\(", "error", "`Tween.new()` is invalid in Godot 4 → `create_tween()`"),
    (r"\.interpolate_property\s*\(", "error", "Godot 3 Tween node → `create_tween().tween_property(...)`"),
    (r"get_tree\s*\(\s*\)\.change_scene\s*\(", "error", "`change_scene()` → `change_scene_to_file()`"),
    (r"\.change_scene_to\s*\(", "error", "`change_scene_to()` → `change_scene_to_packed()`"),
    (r"\bOS\.get_ticks_msec\s*\(|\bOS\.get_ticks_usec\s*\(|\bOS\.get_system_time_msecs\s*\(", "error",
     "`OS.get_ticks_*()` → `Time.get_ticks_msec()` / `Time.get_ticks_usec()`"),
    (r"\bOS\.get_unix_time\s*\(|\bOS\.get_datetime\s*\(", "error",
     "`OS.get_unix_time()/get_datetime()` → `Time.get_unix_time_from_system()` / `Time.get_datetime_dict_from_system()`"),
    (r"\bOS\.window_size\b|\bOS\.get_window_size\s*\(|\bOS\.set_window_size\s*\(", "error",
     "`OS.window_size` → `get_window().size` / `DisplayServer.window_get_size()`"),
    (r"\bOS\.get_screen_size\s*\(|\bOS\.get_screen_dpi\s*\(|\bOS\.get_screen_orientation\s*\(", "error",
     "`OS.get_screen_*()` → `DisplayServer.screen_get_size()/screen_get_dpi()/screen_get_orientation()`"),
    (r"\bOS\.set_window_fullscreen\s*\(|\bOS\.window_fullscreen\b", "error",
     "→ `DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)`"),
    (r"\bOS\.vibrate_handheld\s*\(", "error", "`OS.vibrate_handheld()` → `Input.vibrate_handheld()`"),
    (r"\bEngine\.iterations_per_second\b", "error", "`Engine.iterations_per_second` → `Engine.physics_ticks_per_second`"),
    (r"\.rect_(position|size|min_size|global_position|scale|rotation|pivot_offset)\b", "warning",
     "Control `rect_*` → `position/size/custom_minimum_size/global_position/scale/rotation/pivot_offset`"),
    (r"\.margin_(left|top|right|bottom)\b", "warning", "Control `margin_*` → `offset_*` (anchors/offsets)"),
    (r"\bmove_and_slide\s*\(\s*[^)\s]", "error",
     "Godot 4 `move_and_slide()` takes no arguments — set the `velocity` property first"),
    (r"\bColor\.[a-z][a-z_0-9]*\b(?!\s*\()", "error", "Color constants are UPPER_CASE in Godot 4 (`Color.RED`)"),
    (r"\.remove\s*\(\s*\w+\s*\)", "warning", "`Array.remove(i)` → `remove_at(i)` (DirAccess.remove(path) is still valid)"),
    (r"\.invert\s*\(\s*\)", "warning", "`Array.invert()` → `reverse()`"),
    (r"\.is_valid_integer\s*\(", "error", "`is_valid_integer()` → `is_valid_int()`"),
    (r"\bget_tree\s*\(\s*\)\.set_input_as_handled\s*\(", "error", "→ `get_viewport().set_input_as_handled()`"),
    (r"\.set_collision_(mask|layer)_bit\s*\(|\.get_collision_(mask|layer)_bit\s*\(", "error",
     "`*_collision_*_bit()` → `set_collision_mask_value()/get_collision_layer_value()` (1-based layer numbers)"),
    (r"\.playback_speed\b", "warning", "`AnimationPlayer.playback_speed` → `speed_scale`"),
    (r"\.raise\s*\(\s*\)", "warning", "`CanvasItem.raise()` → `move_to_front()`"),
    (r"\.percent_encode\s*\(|\.http_escape\s*\(", "error", "→ `uri_encode()`"),
    (r"\bInput\.is_action_pressed\s*\(\s*\"\"\s*,\s*\w+\s*\)", "warning",
     "second argument of is_action_pressed() is `exact_match: bool` in Godot 4"),
))

_TYPE_POSITIONS = (
    re.compile(r"^\s*extends\s+([A-Z][A-Za-z0-9_]*)\s*$", re.M),
    re.compile(r":\s*([A-Z][A-Za-z0-9_]*)\s*(?:=|,|\)|$|:)", re.M),            # var x: Type / param: Type
    re.compile(r"->\s*([A-Z][A-Za-z0-9_]*)\s*:"),                               # -> ReturnType:
    re.compile(r"\b([A-Z][A-Za-z0-9_]*)\.new\s*\("),                             # Type.new(
    re.compile(r"\b(?:as|is)\s+([A-Z][A-Za-z0-9_]*)\b"),                          # as Type / is Type
    re.compile(r"Array\[\s*([A-Z][A-Za-z0-9_]*)\s*\]"),                          # Array[Type]
    re.compile(r"Dictionary\[\s*([A-Z][A-Za-z0-9_]*)\s*,"),                      # Dictionary[Key, ...]
    re.compile(r"Dictionary\[\s*[A-Za-z0-9_]+\s*,\s*([A-Z][A-Za-z0-9_]*)\s*\]"),  # Dictionary[..., Value]
)
_STRIP_STRINGS_RE = re.compile(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'')
_COMMENT_RE = re.compile(r"#.*$")


@dataclass
class LintFinding:
    line: int
    severity: str          # error | warning
    message: str

    def __str__(self) -> str:
        return f"line {self.line}: [{self.severity}] {self.message}"


def user_classes(scripts: Iterable[tuple[str, str]]) -> set[str]:
    """Names a project defines itself: ``class_name X``, inner ``class X:``, ``enum X {``, ``const X = …``."""
    names: set[str] = set()
    for _, text in scripts:
        names.update(re.findall(r"^\s*class_name\s+([A-Z][A-Za-z0-9_]*)", text, re.M))
        names.update(re.findall(r"^\s*class\s+([A-Z][A-Za-z0-9_]*)\s*(?:extends\s+[\w.]+)?\s*:", text, re.M))
        names.update(re.findall(r"^\s*enum\s+([A-Z][A-Za-z0-9_]*)\s*\{", text, re.M))
        names.update(re.findall(r"^\s*(?:static\s+)?const\s+([A-Z][A-Za-z0-9_]*)\s*(?::\s*\w+\s*)?:?=", text, re.M))
    return names


def _clean(raw: str) -> str:
    return _COMMENT_RE.sub("", _STRIP_STRINGS_RE.sub('""', raw))


def lint_script(text: str, index: ApiIndex | None, known: set[str] | None = None) -> list[LintFinding]:
    """Cheap static findings: Godot-3 idioms and class names that do not exist in the pinned engine.

    Only the *same-file* declarations are added to ``known`` automatically; pass the
    project-wide set from :func:`user_classes` for cross-file classes.
    """
    known = set(known or ()) | user_classes([("", text)])
    findings: list[LintFinding] = []
    for i, raw in enumerate(text.splitlines(), 1):
        code = _clean(raw)
        if not code.strip():
            continue
        for pat, severity, hint in LEGACY_PATTERNS:
            if pat.search(code):
                findings.append(LintFinding(i, severity, hint))
        if index is None:
            continue
        seen: set[str] = set()
        for pos in _TYPE_POSITIONS:
            for m in pos.finditer(code):
                name = m.group(1)
                if (name in seen or name in BUILTIN_TYPES or name in known or index.has(name)
                        or name.upper() == name):          # ALL_CAPS → a constant, not a type
                    continue
                seen.add(name)
                if name in LEGACY_CLASS_RENAMES:
                    note = LEGACY_CLASS_NOTES.get(name)
                    findings.append(LintFinding(i, "error", f"{name} is a Godot 3 class — in Godot 4 use "
                                                f"{LEGACY_CLASS_RENAMES[name]}" + (f" ({note})" if note else "")))
                else:
                    sugg = index.suggest(name)
                    findings.append(LintFinding(
                        i, "warning",
                        f"class {name} does not exist in Godot {index.engine_tag}"
                        + (f" (did you mean {', '.join(sugg)}?)" if sugg else "")
                        + " — if it is your own class, declare it with class_name"))
    return findings


def lint_project(project: Path, index: ApiIndex | None) -> dict[str, list[LintFinding]]:
    from .verify import gd_scripts  # local import: verify imports this module for the advisory step
    project = Path(project)
    scripts = [(p.relative_to(project).as_posix(), p.read_text(encoding="utf-8", errors="replace"))
               for p in gd_scripts(project)]
    known = user_classes(scripts)
    out: dict[str, list[LintFinding]] = {}
    for rel, text in scripts:
        f = lint_script(text, index, known)
        if f:
            out[rel] = f
    return out


def format_findings(findings: dict[str, list[LintFinding]], limit: int = 60) -> list[str]:
    lines = [f"{rel}:{f.line}: [{f.severity}] {f.message}" for rel, fs in findings.items() for f in fs]
    if len(lines) > limit:
        lines = lines[:limit] + [f"… {len(lines) - limit} more"]
    return lines
